#!/usr/bin/python3.6


import argparse

parser =  argparse.ArgumentParser(description="Search for IP address including partial IP")
parser.add_argument('snippet', help='IP Address (example: 172.16.20.1)')

args = parser.parse_args()
snippet = args.snippet.lower()

with open('log_ip.txt') as f:
	words = f.readlines()
# previous way to do without list comprehension
#matches = []
#
#for word in words:
#    if snippet in word.lower():
#        matches.append(word)

matches = [word for word in words if snippet in word.lower()]


with open('log_match.txt', 'a') as f:
    
    for line in matches:
        f.write(line)
        print(line)


print(matches)
